---
name: Module-Mask-Deps
version: 0.05
author:
  - 'Matt Lawrence <mattlaw@cpan.org>'
abstract: Mask modules not listed as dependencies
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::CoreList: 1.01
  Module::Mask: 0
  perl: 5.8
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Module::Mask::Deps:
    file: lib/Module/Mask/Deps.pm
    version: 0.05
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
