---
name: Module-Mask-Deps
version: 0.01
author:
  - 'Matt Lawrence <mattlaw@cpan.org>'
abstract: Mask modules not listed as dependencies
license: perl
requires:
  Module::CoreList: 1.01
  Module::Mask: 0
  perl: 5.8
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
build_requires:
  File::Find::Rule: 0
  Test::More: 0
provides:
  Module::Mask::Deps:
    file: lib/Module/Mask/Deps.pm
    version: 0.01
generated_by: Module::Build version 0.2611
